source "https://rubygems.org"

gem "rails", "~> 7.2"
gem "sqlite3", "~> 1.7"

group :development, :test do
  gem "rspec-rails",                    "~> 6.1"
  gem "factory_bot_rails",              "~> 6.4"
  gem "faker",                          "~> 3.2"
  gem "database_cleaner-active_record", "~> 2.1"
  gem "shoulda-matchers",               "~> 6.0"
end
